### ISSUE TITLE
V2.0.0b: error in Logs

### ISSUE THREAD

**Issue by bouwew** [claytonjn/hass-circadian_lighting#111]
After updating to v2.0.0b I see this error, and the lights don't change in color:

```
Log Details (ERROR)
Logger: homeassistant
Source: custom_components/circadian_lighting/switch.py:381
First occurred: 8:24:57 PM (9 occurrences)
Last logged: 8:24:57 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/circadian_lighting/switch.py", line 381, in _light_state_changed
    if to_state.state == "on" and from_state.state != "on":
AttributeError: 'NoneType' object has no attribute 'state'
```

This is on HA-Core/hassio v0.114.3.

**Comment by mrplow** [comment]
I'm seeing the same error after updating to 2.0.0b via HACS except a different line #.
```
2020-09-04 09:50:32 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/circadian_lighting/switch.py", line 385, in _light_state_changed
    if to_state.state == "on" and from_state.state != "on":
AttributeError: 'NoneType' object has no attribute 'state'
```

**Comment by basnijholt** [comment]
Thanks for reporting! I'll make a PR in a few hours with the fix.

**Comment by basnijholt** [comment]
https://github.com/claytonjn/hass-circadian_lighting/pull/112/ should fix it this.

**Comment by basnijholt** [comment]
@mrplow @bouwew could you try if that PR fixes the error?

**Comment by bouwew** [comment]
I've tried using the updated code: no change, both with the old and the new code I cannot manually turn on a switch, which is a new symptom I've just noticed.
With the new code there is no error in Logs, that's the positive change.

**Comment by basnijholt** [comment]
What do you mean with manually turning on a switch? You mean you cannot turn on the switch.circadian_lightning switch? Or the light switch of a light that appears in de circadian_lightning switch?

**Comment by bouwew** [comment]
I mean I cannot turn on the circadian switch.

**Comment by basnijholt** [comment]
Could you share your config entry? It work fine for me but probably your configuration is different.

**Comment by bouwew** [comment]
```
switch:
  - platform: circadian_lighting
    name: woonkamer_clr
    lights_ct:
      - light.staande_lamp_1
      - light.staande_lamp_2
    initial_transition: 0
    disable_brightness_adjust: true
  - platform: circadian_lighting
    name: woonkamer_br
    lights_brightness:
      - light.staande_lamp_1
      - light.staande_lamp_2
    max_brightness: 20
    initial_transition: 0
```

This is how all my switches look like, 2 per light(-group).

**Comment by basnijholt** [comment]
Thanks, I will check it out later when I get home. Just to be sure, when you have to switch in Lovelace (or states panel) you can't toggle it on?

**Comment by mrplow** [comment]
Your PR didn't fix the issue for me. The error went away but when trying to turn the circadian lighting switch on from the dashboard it turns itself back off after a second. Here are some debug logs but they don't appear to be useful.

```
2020-09-05 09:06:00 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload for type get_config: {}
2020-09-05 09:06:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140426868170816] Received {'type': 'call_service', 'domain': 'switch', 'service': 'turn_on', 'service_data': {'entity_id': 'switch.circadian_lighting_circadian_lighting'}, 'id': 23}
2020-09-05 09:06:00 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=switch, service=turn_on, service_data=entity_id=switch.circadian_lighting_circadian_lighting>
2020-09-05 09:06:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140426868170816] Sending {'id': 23, 'type': 'result', 'success': True, 'result': {'context': Context(user_id='248eec6876d24ee4bf75a823ec66ce75', parent_id=None, id='b0fd9b00ef9111ea9de4e786c2bc234c')}}
2020-09-05 09:06:01 DEBUG (MainThread) [homeassistant.components.hue.light] Finished fetching group data in 0.015 seconds
2020-09-05 09:06:01 DEBUG (MainThread) [homeassistant.components.hue.light] Finished fetching light data in 0.029 seconds
2020-09-05 09:06:01 DEBUG (MainThread) [homeassistant.components.hue.sensor_base] Finished fetching sensor data in 0.043 seconds
```

**Comment by basnijholt** [comment]
I can indeed also reproduce the issue. The code in the pull request fixes another problem actually.￼

I will post a fix in a few hours!

Sorry about the problem.￼

**Comment by basnijholt** [comment]
The problem should be fixed now (see the PR).

I had never actually tried switching on and off the switch after I made the change to async... My bad.

**Comment by bouwew** [comment]
Thanks! I can confirm, the circadian-switches can be toggled on and off now.
More testing when it gets dark again...
