### PR TITLE
Wait for astral to have attribute 'location' before using it

### LINKED ISSUE #149: 2021.5.0
not work with new version 2021.5.0

### LINKED ISSUE #175: Setup Issues
Hi Installed from HACS.  I get the following error on restart.

Logger: homeassistant.setup
Source: custom_components/circadian_lighting/__init__.py:206
Integration: circadian_lighting (documentation, issues)
First occurred: 8:17:00 AM (1 occurrences)
Last logged: 8:17:00 AM

Error during setup of component circadian_lighting
Traceback (most recent call last):
  File "/config/custom_components/circadian_lighting/__init__.py", line 204, in _get_sun_events
    location = astral.location.Location()
AttributeError: module 'astral' has no attribute 'location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 108, in setup
    hass.data[DOMAIN] = CircadianLighting(
  File "/config/custom_components/circadian_lighting/__init__.py", line 157, in __init__
    self._percent = self.calc_percent()
  File "/config/custom_components/circadian_lighting/__init__.py", line 260, in calc_percent
    today = self._relevant_events(now)
  File "/config/custom_components/circadian_lighting/__init__.py", line 251, in _relevant_events
    sun_events = self._get_sun_events(now + timedelta(days=days))
  File "/config/custom_components/circadian_lighting/__init__.py", line 206, in _get_sun_events
    location = astral.Location()
AttributeError: module 'astral' has no attribute 'Location'

### PR DESCRIPTION
**Pull request by ullebe1**
Sometimes while initializing the component the `astral` module doesn't have the `location` attribute yet when the component tries to use it, cause bugs like  #148, #149 and #175.

This PR implements a loop that causes initialization to wait another second if the attribute isn't available yet. If it still isn't available after 30 seconds we let the initialization continue and crash, like before.

I have been running with a simpler version of the fix (a single 10 second sleep) for months, which has completely fixed the issue for me, but this version is a bit more clever to avoid waiting longer than necessary while also being more resilient in case longer is needed.

Closes #149, closes #175.

### CODE REVIEW

**Comment by amaisano** [comment]
Same problem. Please merge! The patch fixes the issue for me.

**Comment by ullebe1** [comment]
> I'd feel better if this used asyncio.sleep

The component is currently not async, so would it make sense to mix async into without converting the whole thing?
Also, made a quick test with it using `asyncio.sleep`, but when using that the fix didn't work anymore - perhaps because of the above?

> Also, is there a similar problem with the location = astral.Location() call in the except block? If memory serves me right, this call is for astral 1.x.

It looks like it isn't present in 2.x as their [docs](https://astral.readthedocs.io/en/latest/package.html#astral.location.Location) point to `astral.location.Location()`.

**Comment by claytonjn** [comment]
I actually have an async version running locally and will push that out as a new beta release as soon as I get a chance. That being said, I don't think this is required after #189 and using the homeassistant helper is likely a better solution. 

@ullebe1 @amaisano can you confirm if 2.0.8-beta fixes this issue for you?

**Comment by ullebe1** [comment]
@claytonjn 2.0.8-beta fixes it for me, great if we don't need this workaround anyway.

Also a future async version sounds awesome - thank you!

**Comment by ullebe1** [comment]
@claytonjn I just wanted to report back that after testing the 2.0.8-beta for the last two weeks it works great and completely solved the issue.

**Comment by claytonjn** [comment]
I've pushed this to the main branch and have the async code in the dev (beta) branch, so will close this.
