### PR TITLE
feature: support both Astral v2 and v1 API

### PR DESCRIPTION
**Pull request by emansom**
The Astral library changed their API somewhat. When using this plugin on a rolling-release distro it lead to breakage.

### CODE REVIEW

**Comment by claytonjn** [comment]
Awesome, I have a lot going on right now but I'll get this merged ASAP. Thanks!

File: custom_components/circadian_lighting/__init__.py [hunk 1]
```diff
@@ -164,6 +164,10 @@ def get_sunrise_sunset(self, date = None):
         else:
             import astral
             location = astral.Location()
```
Comment (vimeh) [inline custom_components/circadian_lighting/__init__.py:166]: del this line, that got it working again for me

**Review by pijiulaoshi — APPROVED** [review]
This fixes the issues I ran into as well.
I changed everything to v2 in my own ha setup, but the fix proposed here is better.

File: custom_components/circadian_lighting/__init__.py (hunk 1 above)
Comment (rubdos) [inline custom_components/circadian_lighting/__init__.py:166]: You may want to drop this old line, since your try-except block replaces this. Gave me this otherwise:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/circadian_lighting/__init__.py", line 109, in setup
    cl = CircadianLighting(hass, min_colortemp, max_colortemp,
  File "/config/custom_components/circadian_lighting/__init__.py", line 139, in __init__
    self.data['percent'] = self.calc_percent()
  File "/config/custom_components/circadian_lighting/__init__.py", line 220, in calc_percent
    today_sun_times = self.get_sunrise_sunset(now)
  File "/config/custom_components/circadian_lighting/__init__.py", line 174, in get_sunrise_sunset
    location = astral.Location()
AttributeError: module 'astral' has no attribute 'Location'
```

**Comment by cwildfoerster** [comment]
Not working on 2020.5, even with @rubdos change.

**Comment by rubdos** [comment]
> Not working on 2020.5, even with @rubdos change.

What error do you still have? Together with the patch for the `version` field, this works for me.

**Comment by ruifung** [comment]
> 
> 
> Not working on 2020.5, even with @rubdos change.

Same here, for some reason I needed to do
```
import astral.location as astralLocation
location = astralLocation.Location()
```
for it to work, seems like importing the package astral doesn't import the module location... 

Running HASS Container in docker.

File: custom_components/circadian_lighting/__init__.py [hunk 2]
```diff
@@ -184,8 +187,14 @@ def get_sunrise_sunset(self, date = None):
...
-            solar_noon = location.solar_noon(date)
-            solar_midnight = location.solar_midnight(date)
+            try:
+              solar_noon = location.noon(date)
+            except AttributeError:
+              solar_noon = location.solar_noon(date)
+            try:
+              solar_midnight = location.midnight(date)
+            except AttributeError:
+              solar_midnight = location.solar_midnight(date)
```
Comment (BenoitAnastay) [inline custom_components/circadian_lighting/__init__.py:197]: May be simplified this way

```python
            try:
                solar_noon = location.noon(date)
                solar_midnight = location.midnight(date)
            except AttributeError:
                solar_noon = location.solar_noon(date)
                solar_midnight = location.solar_midnight(date)
```
